version: '3.8'
services:
    mysql:
        image: mariadb
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        networks:
            - inception_custom
        volumes:
            - db:/var/lib/mysql
        env_file: .env
        restart: always

        #healthcheck:
        #    test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        #    timeout: 5s
        #    retries: 10

    wordpress:
        image: wordpress
        container_name: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        depends_on:
            - mysql
            - redis
        #    mysql:
        #        condition: service_healthy
        networks:
            - inception_custom
        volumes:
            - wp:/var/www/html
        env_file: .env
        restart: always

    nginx:
        image: nginx
        container_name: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        depends_on:
            - wordpress
        networks:
            - inception_custom
        volumes:
            - wp:/var/www/html
        restart: always

    redis:
        image: redis
        container_name: redis
        build:
            context: ./bonus/redis
            dockerfile: Dockerfile
        ports:
            - '6379:6379'
        volumes:
            - 'wp:/var/www/html'
        networks:
            - inception_custom
        restart: always

    ftp:
        image: vsftpd
        container_name: vsftpd
        build:
            context: ./bonus/ftp
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - '21:21'
            - '30001-30010:30001-30010'
        depends_on:
            - wordpress
        networks:
            - inception_custom
        volumes:
            - 'wp:/var/www/html'
        restart: always


volumes:
    wp:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            device: /home/lpeggy/data/wp
            o: bind
    db:
        name: db
        driver: local
        driver_opts:
            type: none
            device: /home/lpeggy/data/db
            o: bind

networks:
    inception_custom:
        name: inception_custom
        driver: bridge
