version: '3.9'
services:

	mariadb:
		image: mariadb
		build:
            context: ./mariadb #
            dockerfile: Dockerfile
# create two users
		volumes: /home/lpeggy/data #for wp and db
		environment:
			# name, password, user
		restart_policy:
            condition: on-failure

	wordpress:
		image: wordpress
		build:
            context: ./wordpress #
            dockerfile: Dockerfile
		dependency:
			- mariadb
		volumes: /home/lpeggy/data #for wp and db
		restart_policy:
            condition: on-failure #any
	nginx:
		image: nginx
		build:
            context: ./nginx #
            dockerfile: Dockerfile
		ports:
			- 443:443
		#extra_hosts: #ports(?)
        #   lpeggy.42.fr
        dependency:
			- wordpress
		restart_policy:
            condition: on-failure
